name: grassroots_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  http: ^0.13.3
  path_provider: ^2.0.3
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.10
  cached_network_image: ^3.1.0
  device_info_plus: ^4.0.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  rxdart: ^0.26.0
  flutter_svg: ^0.22.0
  contacts_service: ^0.4.6
  flutter_bloc: ^8.1.1
  # flutter_local_notifications: ^8.2.0
  firebase_core: ^1.12.0
  firebase_messaging: ^10.0.7
  flutter_secure_storage: ^3.3.3
  intl: ^0.16.1
  get_storage: ^2.0.1
  shared_preferences: ^2.0.7
  dynamic_color: ^1.5.4
  google_fonts: ^2.1.0
  flutter_screenutil: ^5.1.1
  intl_phone_number_input: ^0.7.1
  pin_code_text_field: ^1.8.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
          - asset: assets/fonts/Roboto-Black.ttf
          - asset: assets/fonts/Roboto-Bold.ttf
          - asset: assets/fonts/Roboto-Light.ttf
          - asset: assets/fonts/Roboto-Medium.ttf
          - asset: assets/fonts/Roboto-Regular.ttf
          - asset: assets/fonts/Roboto-Thin.ttf
          - asset: assets/fonts/Roboto-BlackItalic.ttf
            style: italic
          - asset: assets/fonts/Roboto-BoldItalic.ttf
            style: italic
          - asset: assets/fonts/Roboto-Italic.ttf
            style: italic
          - asset: assets/fonts/Roboto-LightItalic.ttf
            style: italic
          - asset: assets/fonts/Roboto-MediumItalic.ttf
            style: italic
          - asset: assets/fonts/Roboto-ThinItalic.ttf
            style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
